### ISSUE TITLE
[enhancement/refactor] switch from docker to podman

### ISSUE THREAD

**Issue by pinkcreeper100** [Bijman/srb2bld#17]
podman doesn't have a daemon and is rootless

**Comment by Bijman** [comment]
Not going to replace `docker`, since it is more widely available in Linux distributions, especially in currently supported Ubuntu LTS releases and has less issues with "permission denied" messages and less to do in program's setup to make it work in some Linux distributions, but if someone wants to use and has installed `podman`, this will be used over `docker`.

**Comment by Bijman** [comment]
Not going to replace docker at this moment, since it is more widely available in Linux distributions, especially in currently supported Ubuntu LTS releases and has less issues of "permission denied" and less steps to setup program to make it work in some Linux distributions, but if someone wants to use and has installed podman, this will be used over docker.

BTW Docker can be rootless too: https://docs.docker.com/engine/security/rootless/

**Comment by pinkcreeper100** [comment]
> BTW Docker can be rootless too: https://docs.docker.com/engine/security/rootless/

didn't know that, interesting

**Comment by Bijman** [comment]
Implemented support for podman with commit eb2fd35.
