### ISSUE TITLE
v2.1.12 pre-3 doesn't compile, for some reason (using the new docker build)

### ISSUE THREAD

**Issue by EeveeEuphoria** [Bijman/srb2bld#23]
I'm wholly unsure why this doesn't compile, since it compiles just fine on opensuse, and someone else's machine (not with srb2bld), using the docker found in the commit https://github.com/Bijman/srb2bld/commit/6c34f0284a1452a8eded08d7bd02699e58aa9989

Here's a crash log:
[crash-log.txt](https://github.com/Bijman/srb2bld/files/12388953/crash-log.txt)
And maybe some relevant compiler errors:
[message.txt](https://github.com/Bijman/srb2bld/files/12388960/message.txt)

**Comment by Bijman** [comment]
That SIGABRT signal issue occurs, if I compiled v2.1.12 pre-3 on my Gentoo and Ubuntu 18.04 LTS and Ubuntu 20.04 LTS, so likely the issue is with the game's code that affects some Linux distributions. This needs to be reported to developers of SRB2. Not sure, if this is the same case when I got SIGABRT with SRB2 rphys, which I reported in SRB2 MB.

You can try to use one workaround with CFLAGS="-D_FORTIFY_SOURCE=0" when entering this as compilation flag in srb2bld for the time being, but probably not recommended in the long run.

**Comment by EeveeEuphoria** [comment]
i see, i talked about this in the SRB2 discord, and when i'm not busy dealing with data recovery (oops), i'll spin up an ubuntu VM to recreate this and submit relevant logs

**Comment by EeveeEuphoria** [comment]
Just an update, RC1 is out and that seems to compile fine; katsy was able to fix up the issues from pre3 up to RC1!

**Comment by Bijman** [comment]
I can confirm that it compiles and runs successfully with RC1 for Gentoo, Ubuntu 18.04 LTS and Ubuntu 20.04 LTS.
