### ISSUE TITLE
SRB2 rphys uses .srb2 rather than its own folder

### ISSUE THREAD

**Issue by pinkcreeper100** [Bijman/srb2bld#5]

**Comment by Bijman** [comment]
This is expected behavior for builds added to script's list related to current SRB2 release with default branch, except for old releases of SRB2 and unique forks like SRB2 Kart and SRB2 Persona. Although one potential issue in the future would be conflicts between new release of SRB2 and builds that didn't update to this release sharing the same `.srb2` folder, so I would consider renaming config folders for each SRB2 related build.
